include:
  - template: Security/Container-Scanning.gitlab-ci.yml

variables:
  FROM_IMAGE_NAME: "almalinux"
  FROM_IMAGE_TAG: "9.4-minimal-20240723"
  TERRAFORM_VERSION: "1.9.4"
  TERRAFORM_DOCS_VERSION: "0.18.0"
  TERRAGRUNT_VERSION: "0.66.8"
  TFSEC_VERSION: "1.28.6"
  TFLINT_VERSION: "0.53.0"
  GITLEAKS_VERSION: "8.18.4"

stages:
  - build
  - test
  - cleanup
  - release

kaniko-build:
  stage: build
  image:
    # The kaniko debug image is recommended (gcr.io/kaniko-project/executor:debug) because it has a shell,
    # and a shell is required for an image to be used with GitLab CI/CD.
    # Kaniko Release: https://github.com/GoogleContainerTools/kaniko/releases
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  # Use kaniko to build Docker images
  # https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
      --build-arg FROM_IMAGE_NAME=${FROM_IMAGE_NAME}
      --build-arg FROM_IMAGE_TAG=${FROM_IMAGE_TAG}
      --build-arg TERRAFORM_VERSION=${TERRAFORM_VERSION}
      --build-arg TERRAFORM_DOCS_VERSION=${TERRAFORM_DOCS_VERSION}
      --build-arg TERRAGRUNT_VERSION=${TERRAGRUNT_VERSION}
      --build-arg TERRASCAN_VERSION=${TERRASCAN_VERSION}
      --build-arg TFSEC_VERSION=${TFSEC_VERSION}
      --build-arg TFLINT_VERSION=${TFLINT_VERSION}
      --build-arg GITLEAKS_VERSION=${GITLEAKS_VERSION}
  rules:
    - if: $CI_COMMIT_TAG

container_scanning:
  # https://docs.gitlab.com/ee/user/application_security/container_scanning/#available-cicd-variables
  variables:
    # Repository: Self Repo
    CS_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    CS_DOCKERFILE_PATH: Dockerfile
    GIT_STRATEGY: fetch
    SECURE_LOG_LEVEL: info
    CS_SEVERITY_THRESHOLD: LOW
  needs: ["kaniko-build"]
  rules:
    - if: $CI_COMMIT_TAG

check_container_scanning:
  stage: test
  image: alpine:latest
  variables:
    # If ALLOW_FAILURE is set to true, the job will not fail regardless of the count of high and critical vulnerabilities.
    # If ALLOW_FAILURE is set to false, the job will fail if high or critical vulnerabilities are found.
    ALLOW_FAILURE: false
  allow_failure: false # Allows this job to fail without marking the entire pipeline as failed
  script:
    - >
      apk update &&
      apk add jq &&
      HIGH_COUNT=$(cat ./gl-container-scanning-report.json | jq '.vulnerabilities | map(select(.severity=="High")) | length') &&
      CRITICAL_COUNT=$(cat ./gl-container-scanning-report.json | jq '.vulnerabilities | map(select(.severity=="Critical")) | length') &&
      MEDIUM_COUNT=$(cat ./gl-container-scanning-report.json | jq '.vulnerabilities | map(select(.severity=="Medium")) | length') &&
      LOW_COUNT=$(cat ./gl-container-scanning-report.json | jq '.vulnerabilities | map(select(.severity=="Low")) | length') &&
      UNKNOWN_COUNT=$(cat ./gl-container-scanning-report.json | jq '.vulnerabilities | map(select(.severity=="Unknown")) | length') &&
      FAIL_COUNT=$((HIGH_COUNT + CRITICAL_COUNT)) &&
      TOTAL_COUNT=$((HIGH_COUNT + CRITICAL_COUNT + MEDIUM_COUNT + LOW_COUNT + UNKNOWN_COUNT)) &&
      echo "Number of high vulnerabilities: ${HIGH_COUNT}" &&
      echo "Number of critical vulnerabilities: ${CRITICAL_COUNT}" &&
      echo "Number of medium vulnerabilities: ${MEDIUM_COUNT}" &&
      echo "Number of low vulnerabilities: ${LOW_COUNT}" &&
      echo "Number of unknown vulnerabilities: ${UNKNOWN_COUNT}" &&
      echo "Total vulnerabilities: ${TOTAL_COUNT}" &&
      if [ $ALLOW_FAILURE = "true" ]; then
        if [ $FAIL_COUNT -gt 0 ]; then
          echo "High and critical vulnerabilities found. ALLOW_FAILURE is true. Job will not fail regardless of FAIL_COUNT."
          exit 1
        else
          echo "No high or critical vulnerabilities found. ALLOW_FAILURE is true. Job will not fail."
          exit 0
        fi
      else
        if [ $FAIL_COUNT -gt 0 ]; then
          echo "High and critical vulnerabilities found. Exiting with status 1."
          exit 1
        else
          echo "No high or critical vulnerabilities found. Exiting with status 0."
          exit 0
        fi
      fi
  needs:
    - job: container_scanning
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG

terraform_check:
  stage: test
  image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  script:
    - terraform --version || echo "Terraform command failed"
  rules:
    - if: $CI_COMMIT_TAG

terraform_docs_check:
  stage: test
  image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  script:
    - terraform-docs --version || echo "Terraform Docs command failed"
  rules:
    - if: $CI_COMMIT_TAG

terragrunt_docs_check:
  stage: test
  image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  script:
    - terragrunt --version || echo "Terragrunt command failed"
  rules:
    - if: $CI_COMMIT_TAG

tfsec_check:
  stage: test
  image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  script:
    - tfsec --version || echo "tfsec command failed"
  rules:
    - if: $CI_COMMIT_TAG

tflint_check:
  stage: test
  image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  script:
    - tflint --version || echo "TFLint command failed"
  rules:
    - if: $CI_COMMIT_TAG

gitleaks_check:
  stage: test
  image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  script:
    - gitleaks version || echo "Gitleaks command failed"
  rules:
    - if: $CI_COMMIT_TAG

checkov_check:
  stage: test
  image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  script:
    - checkov --version || echo "checkov command failed"
  rules:
    - if: $CI_COMMIT_TAG

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Running the release job."
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'Release $CI_COMMIT_TAG'
    description: 'Release created using the release-cli.'
  needs: ["check_container_scanning"]
  rules:
    - if: $CI_COMMIT_TAG

# In a CI/CD pipeline, remove a Git tag if a build fails.
delete_remote_tag:
  stage: cleanup
  image: docker:24.0.6-git
  script:
    - git remote set-url origin https://PAC_IAC_CICD_1:${PAC_IAC_CICD_1}@gitlab.jodywan.com/container-dev/iac-cicd.git
    - git remote -v
    - git push --delete origin $CI_COMMIT_TAG
  when: on_failure
  rules:
    - if: $CI_COMMIT_TAG

delete_repository_tag:
  stage: cleanup
  image: badouralix/curl-jq:alpine
  script:
    - echo "List registry repositories."
    # Make the API request and save the response to a variable
    - |
      RESPONSE=$(curl --header "PRIVATE-TOKEN: ${PAC_IAC_CICD_1}" \
      "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/registry/repositories");
    - echo $RESPONSE
    # Parse the response JSON and extract the repository_id value  repository_id
    - REPOSITORY_ID=$(echo "$RESPONSE" | jq -r '.[0].id')
    - echo $REPOSITORY_ID
    # Get details of a registry repository tag
    - echo "Get details of a registry repository tag."
    - |
      curl --header "PRIVATE-TOKEN: ${PAC_IAC_CICD_1}" \
      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/registry/repositories/$REPOSITORY_ID/tags/${CI_COMMIT_TAG}";
    # Check the if registry image exists in the gitlab container registry.
    - echo "Check the if registry image exists in the gitlab container registry."
    - |
      curl -o /dev/null -s -w "%{http_code}\n" --header "PRIVATE-TOKEN: ${PAC_IAC_CICD_1}" \
      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/registry/repositories/$REPOSITORY_ID/tags/${CI_COMMIT_TAG}" -f;
    # Delete a registry repository tag.
    - echo "Delete a registry repository tag."
    - |
      curl --request DELETE --header "PRIVATE-TOKEN: ${PAC_IAC_CICD_1}" \
          "$CI_API_V4_URL/projects/$CI_PROJECT_ID/registry/repositories/$REPOSITORY_ID/tags/${CI_COMMIT_TAG}" -f;
  when: on_failure
  rules:
    - if: $CI_COMMIT_TAG